name: spreed-webrtc
version: 0.24.11-2
summary: WebRTC audio/video calls and conferences
description: Spreed WebRTC implements a WebRTC audio/video call and conferencing server and web client
icon: spreedWaves.svg
confinement: strict

apps:
  spreed-webrtc:
    command: bin/start
    daemon: simple
    restart-condition: always
    plugs: [network,network-bind]

parts:
  spreed:
    plugin: autotools
    source: https://github.com/strukturag/spreed-webrtc
    source-type: git
    source-branch: develop
    build-packages: [golang-go, nodejs]
    stage-packages: [openssl]
  glue:
    plugin: copy
    files:
      start: bin/start
      redirector: bin/redirector
      config.py: bin/config
      config/*: config/
